/*
 * Copyright 2017 Adrien "Litarvan" Navratil
 *
 * This file is part of Krobot.
 *
 * Krobot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Krobot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Krobot.  If not, see <http://www.gnu.org/licenses/>.
 */
package fr.litarvan.krobot.command;

import java.util.List;
import org.jetbrains.annotations.Nullable;

/**
 * A Command Group
 *
 *
 * A group generated by the {@link CommandGroup} that contains
 * some properties (like a label prefix, some middlewares) to
 * be applied to some commands.
 *
 * To be used with the {@link GroupBuilder} from
 * {@link CommandManager#group()}
 *
 * @author Litarvan
 * @version 2.0.0
 * @since 2.0.0
 */
public class CommandGroup
{
    private String prefix;
    private Command parent;
    private List<Middleware> middlewares;

    /**
     * A Command group
     *
     * @param prefix A label prefix to apply
     * @param parent A parent command
     * @param middlewares Some middlewares to register
     */
    public CommandGroup(@Nullable String prefix, @Nullable Command parent, @Nullable List<Middleware> middlewares)
    {
        this.prefix = prefix;
        this.parent = parent;
        this.middlewares = middlewares;
    }

    /**
     * @return A label prefix to apply
     */
    @Nullable
    public String getPrefix()
    {
        return prefix;
    }

    /**
     * @return A parent command
     */
    @Nullable
    public Command getParent()
    {
        return parent;
    }

    /**
     * @return Some middlewares to register
     */
    @Nullable
    public List<Middleware> getMiddlewares()
    {
        return middlewares;
    }
}
